name: WHBot
version: 0.2.26
author: Underscore11
main: com.gmail.minecrafter11mrt.whbot.WHBot
description: A plugin-based Discord bot made for the WolvHaven Community. Usage of this plugin without permission from the author is not permitted.